import "./globals.css";
import Footer from "./Components/Footer";
import DarkMode from "./Components/DarkMode";

export const metadata = {
  title: "Cam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <DarkMode />
      <body>
        <main>{children}</main>
      </body>
      <Footer />
    </html>
  );
}
